spring:
  application:
    name: conduit
  datasource: 
    url: jdbc:postgresql://localhost:5433/conduit
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
   hibernate: 
    ddl-auto: update
  
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ajithdhas2003@gmail.com
    password: fkug yddr qrsf gmrz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
    port: 8082