spring:
  application:
    name: user_service
  datasource: 
    url: jdbc:postgresql://localhost:5433/conduit
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
   hibernate: 
    ddl-auto: update
  
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
  data: 
    redis:
      host: localhost
      port: 6379

server:
  port: 9000
